Repository codestates-seb/seb44_main_028, pull requests merged in 2023-07, with the labels that each got.

#83 [FE] Loading 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/common/components/Loading.tsx
  client/src/common/style/style.ts
  client/src/common/utils/enum/colorPalette.ts
Labels: frontend, feat

#82 [FE] Category Checkbox 컴포넌트 구현
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/common/components/Checkbox/Checkbox.tsx
  client/src/common/constants.ts
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/common/utils/enum/borderRadius.ts
  client/src/pages/Create/views/CreatePage.tsx
Labels: frontend, feat

#84 [FE] 검색 결과 데이터 없을 때 NoData 컴포넌트 구현
  client/src/assets/no_data/NoDataImage.svg
  client/src/common/components/NoData.tsx
  client/src/common/constants.ts
  client/src/common/style/style.ts
  client/src/common/utils/enum/fontSize.ts
Labels: frontend, feat

#88 [FE] 메인페이지
  client/src/App.tsx
  client/src/Router.tsx
  client/src/common/components/Category/Category.tsx
  client/src/common/components/Category/CategoryButton.tsx
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/components/ItemCard/ItemCardList.tsx
  client/src/common/components/ScrollToTop.tsx
  client/src/common/constants.ts
  client/src/common/model/ICategory.tsx
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/common/utils/enum/colorPalette.ts
  client/src/pages/Footer/FooterStyles.ts
  client/src/pages/Footer/views/Footer.tsx
  client/src/pages/Header/views/Header.tsx
  client/src/pages/Main/constants.ts
  client/src/pages/Main/style.ts
  client/src/pages/Main/views/MainPage.tsx
  client/src/pages/MyPage/components/BorrowList.tsx
  client/src/pages/MyPage/components/LendList.tsx
  client/src/pages/MyPage/components/ParentTap.tsx
  client/src/pages/MyPage/components/WishList.tsx
Labels: frontend, feat

#89 [FE] 헤더 UI refactor
  client/src/App.tsx
  client/src/common/utils/enum/colorPalette.ts
  client/src/common/utils/enum/fontSize.ts
  client/src/pages/Header/constants.ts
  client/src/pages/Header/style.ts
  client/src/pages/Header/type.ts
  client/src/pages/Header/views/Header.tsx
Labels: frontend, refactor

#91 [FE] 1차 Modal Refactor
  client/public/index.html
  client/src/common/components/Modal/ModalButton.tsx
  client/src/common/components/Modal/ModalMain.tsx
  client/src/common/components/Modal/ModalTitle.tsx
  client/src/common/type.ts
  client/src/pages/Main/views/MainPage.tsx
Labels: frontend, refactor

#96 [FE] ItemListPage
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/pages/ItemList/style.ts
  client/src/pages/ItemList/views/ItemListPage.tsx
  client/src/pages/Main/views/MainPage.tsx
  client/src/pages/MyPage/components/LendList.tsx
Labels: frontend, feat

#97 [FE] 찜하기 기능
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/constants.ts
  client/src/common/type.ts
  client/src/pages/Main/constants.ts
  client/src/pages/Main/views/MainPage.tsx
Labels: frontend, feat

#103 [FE] 2차 Modal Refactor
  client/src/App.tsx
  client/src/common/components/Button.tsx
  client/src/common/components/Modal/ModalAdditional.tsx
  client/src/common/components/Modal/ModalButton.tsx
  client/src/common/components/Modal/ModalFrame.tsx
  client/src/common/components/Modal/ModalMain.tsx
  client/src/common/components/Modal/ModalPortal.tsx
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/common/utils/enum/colorPalette.ts
  client/src/pages/Booking/components/ReservationBtn.tsx
  client/src/pages/Main/style.ts
  client/src/pages/Main/views/MainPage.tsx
  client/src/pages/MyPage/components/Modal.tsx
  client/src/pages/MyPage/constants.ts
Labels: frontend, refactor

#105 [FE] 404 Error 컴포넌트 구현
  client/src/assets/404_error/404_error.svg
  client/src/common/components/ErrorPage.tsx
  client/src/common/style/style.ts
  client/src/pages/MyPage/constants.ts
Labels: frontend, feat

#133 [FE] 1차 CreatePage 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/common/components/Category/Category.tsx
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/style/style.ts
  client/src/common/utils/enum/colorPalette.ts
  client/src/pages/Create/components/InputField.tsx
  client/src/pages/Create/components/PreImage.tsx
  client/src/pages/Create/components/UploadImage.tsx
  client/src/pages/Create/components/WritePost.tsx
  client/src/pages/Create/constants.ts
  client/src/pages/Create/style.ts
  client/src/pages/Create/type.ts
  client/src/pages/Create/views/CreatePage.tsx
Labels: frontend, feat

#140 [FE] 2차 찜하기 구현
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/components/ItemCard/ItemCardList.tsx
  client/src/common/model/IInterest.tsx
  client/src/common/store/InterestStore.tsx
  client/src/common/store/RootStore.tsx
  client/src/pages/Main/constants.ts
Labels: frontend, feat

#141 [FE] 카테고리 리스트 받아오기
  client/src/common/components/Category/Category.tsx
  client/src/common/components/Category/CategoryButton.tsx
  client/src/common/model/ICategory.tsx
  client/src/pages/ItemList/views/ItemListPage.tsx
Labels: frontend, feat

#162 [FE] 마이페이지 페이지네이션 완료, 카드컴포넌트 생성
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/components/MypageCard/BorrowCard.tsx
  client/src/common/store/RootStore.tsx
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/common/utils/enum/colorPalette.ts
  client/src/pages/Main/constants.ts
  client/src/pages/Main/views/MainPage.tsx
  client/src/pages/MyPage/components/BorrowList.tsx
  client/src/pages/MyPage/components/LendList.tsx
  client/src/pages/MyPage/components/MypageProfile.tsx
  client/src/pages/MyPage/components/ProfileEdit.tsx
  client/src/pages/MyPage/components/WishList.tsx
  client/src/pages/MyPage/components/fetchList.tsx
  client/src/pages/MyPage/constants.ts
  client/src/pages/MyPage/store/ProfileSlice.tsx
  client/src/pages/MyPage/style.ts
  client/src/pages/MyPage/views/MyPage.tsx
Labels: frontend, feat

#163 [FE] 2차 createPage
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/common/components/Checkbox/Checkbox.tsx
  client/src/common/components/Modal/ModalMain.tsx
  client/src/common/components/Modal/modal-guide.md
  client/src/common/type.ts
  client/src/common/utils/enum/colorPalette.ts
  client/src/pages/Create/components/InputField.tsx
  client/src/pages/Create/components/UploadImage.tsx
  client/src/pages/Create/components/WritePost.tsx
  client/src/pages/Create/constants.ts
  client/src/pages/Create/style.ts
  client/src/pages/Create/type.ts
  client/src/pages/Create/views/CreatePage.tsx
  client/src/pages/Footer/FooterStyles.ts
Labels: frontend, feat

#172 [FE] mainPage items
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/style/style.ts
  client/src/pages/Main/views/MainPage.tsx
Labels: frontend, feat

#177 [FE] detail page
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/utils/enum/colorPalette.ts
  client/src/common/utils/enum/fontSize.ts
  client/src/pages/Detail/components/ItemContent.tsx
  client/src/pages/Detail/components/ItemPrice.tsx
  client/src/pages/Detail/components/ItemTag.tsx
  client/src/pages/Detail/components/ItemUserInfo.tsx
  client/src/pages/Detail/constants.ts
  client/src/pages/Detail/style.ts
  client/src/pages/Detail/type.ts
  client/src/pages/Detail/views/DetailPage.tsx
Labels: frontend, feat

#178 [FE] 3차 createPage
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/common/components/Checkbox/Checkbox.tsx
  client/src/common/type.ts
  client/src/pages/Create/components/UploadImage.tsx
  client/src/pages/Create/components/WritePost.tsx
  client/src/pages/Create/style.ts
  client/src/pages/Create/type.ts
  client/src/pages/Create/views/CreatePage.tsx
  client/src/pages/Detail/style.ts
  client/tsconfig.json
Labels: frontend, feat

#179 [FE] 빌린내역 목업 구현
  client/src/pages/MyPage/type.ts
  client/src/pages/MyPage/views/MyPage.tsx
Labels: frontend, feat

#183 [FE] detail Page 구현
  client/package-lock.json
  client/package.json
  client/src/Router.tsx
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/common/components/Checkbox/Checkbox.tsx
  client/src/common/utils/customHooks/useGetMe.tsx
  client/src/pages/Detail/components/ChatBtn.tsx
  client/src/pages/Detail/components/ImageCarousel.tsx
  client/src/pages/Detail/components/ItemContent.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/Detail/type.ts
Labels: frontend, feat

#185 [FE] 페이지 삭제 구현 기능
  client/src/pages/Detail/components/ItemContent.tsx
Labels: frontend, feat

#184 [FE] BorrowList
  client/src/pages/MyPage/components/BorrowList.tsx
  client/src/pages/MyPage/components/MypageProfile.tsx
  client/src/pages/MyPage/components/ParentTap.tsx
  client/src/pages/MyPage/components/ProfileEdit.tsx
  client/src/pages/MyPage/constants.ts
  client/src/pages/MyPage/style.ts
  client/src/pages/MyPage/views/MyPage.tsx
Labels: frontend, feat

#197 [FE] 메인 페이지 items
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/components/ItemCard/ItemCardList.tsx
  client/src/common/type.ts
  client/src/pages/Create/components/WritePost.tsx
  client/src/pages/ItemList/views/ItemListPage.tsx
  client/src/pages/Main/constants.ts
  client/src/pages/MyPage/constants.ts
Labels: bug, frontend

#200 [FE] Category Page
  client/src/common/style/style.ts
  client/src/pages/ItemList/style.ts
  client/src/pages/ItemList/views/ItemListPage.tsx
Labels: frontend, feat

#217 [FE] 상품 CRUD
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/pages/Create/components/UploadImage.tsx
  client/src/pages/Create/components/WritePost.tsx
  client/src/pages/Create/type.ts
  client/src/pages/Create/views/CreatePage.tsx
  client/src/pages/Detail/components/ItemContent.tsx
  client/src/pages/Detail/components/ItemUserInfo.tsx
  client/src/pages/Detail/type.ts
  client/src/pages/Update/model/IProductDetail.ts
  client/src/pages/Update/views/UpdatePage.tsx
Labels: frontend, feat

#218 [FE] 멤버의 위치 정보
  client/src/pages/MyPage/components/MypageProfile.tsx
  client/src/pages/MyPage/components/ProfileEdit.tsx
  client/src/pages/MyPage/model/ILocation.tsx
  client/src/pages/MyPage/style.ts
  client/src/pages/MyPage/type.ts
  client/src/pages/MyPage/utils/customHooks/useGeoLocation.tsx
Labels: frontend, feat

#227 [FE] infinite scroll
  client/package-lock.json
  client/package.json
  client/src/pages/ItemList/components/ItemCardWrapper.tsx
  client/src/pages/ItemList/views/ItemListPage.tsx
  client/src/pages/Main/views/MainPage.tsx
Labels: frontend, feat

#244 [FE] refactor search page
  client/src/Router.tsx
  client/src/common/components/SelectBox.tsx
  client/src/pages/ItemList/views/ItemListPage.tsx
  client/src/pages/Search/views/SearchPage.tsx
Labels: frontend, refactor

#248 [FE] 게시물 patch, delete 수정
  client/src/common/components/Checkbox/CheckBoxList.tsx
  client/src/pages/Create/components/UploadImage.tsx
  client/src/pages/Create/components/WritePost.tsx
  client/src/pages/Detail/components/ItemContent.tsx
  client/src/pages/Update/model/IProductDetail.ts
  client/src/pages/Update/views/UpdatePage.tsx
Labels: frontend, fix

#243 [FE] selecbox option filter
  client/src/common/constants.ts
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/pages/ItemList/type.ts
  client/src/pages/ItemList/views/ItemListPage.tsx
  client/src/pages/Search/views/SearchPage.tsx
Labels: frontend, feat

#255 [FE] 화면 리뷰 후 수정, 마이페이지 진행 중
  client/package-lock.json
  client/package.json
  client/src/assets/logo/logo.svg
  client/src/common/components/ItemCard/ItemCard.tsx
  client/src/common/components/MypageCard/BorrowCard.tsx
  client/src/common/components/MypageCard/LendCard.tsx
  client/src/common/model/ILendCard.tsx
  client/src/common/style/style.ts
  client/src/common/type.ts
  client/src/common/utils/customHooks/useScrollToTop.tsx
  client/src/pages/Booking/views/BookingPage.tsx
  client/src/pages/Create/views/CreatePage.tsx
  client/src/pages/Detail/components/ItemContent.tsx
  client/src/pages/Detail/views/DetailPage.tsx
  client/src/pages/Header/views/Header.tsx
  client/src/pages/ItemList/type.ts
  client/src/pages/ItemList/views/ItemListPage.tsx
  client/src/pages/Login/views/RedirectPage.tsx
  client/src/pages/Main/constants.ts
  client/src/pages/Main/views/MainPage.tsx
  client/src/pages/MyPage/components/BorrowList.tsx
  client/src/pages/MyPage/components/LendList.tsx
  client/src/pages/MyPage/components/MypageProfile.tsx
  client/src/pages/MyPage/components/ProfileEdit.tsx
  client/src/pages/MyPage/components/WishList.tsx
  client/src/pages/MyPage/helper/addressForMatter.ts
  client/src/pages/MyPage/views/MyPage.tsx
Labels: frontend, feat, fix
